local SERVICES = {
	FORWARD_CLOSE			= 0x4E,
	UNCONNECTED_SEND		= 0x52,
	FORWARED_OPEN			= 0x54,
	GET_CONNECTION_DATA		= 0x56,
	SEARCH_CONNECTION_DATA	= 0x57,
	GET_CONNECTION_OWNER	= 0x5A,
	LARGE_FORWARD_OPEN		= 0x5B,
}


return {
	SERVICES = SERVICES
}
